# Version
version: 2.1
# Collective of commands to be executed within pipeline
jobs:
  run_tests:
    # Define where the source code is going to run (executor)
    docker:
      # Define image
      - image: circleci/node:10
      - image: cimg/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: MYSQL_PASS
          MYSQL_DATABASE: world
          MYSQL_USER: thelastchance
          MYSQL_PASSWORD: MYSQL_PASS
    # Define the commands that will happen within the code
    steps:
      # Alias for git clone
      - checkout
      # Run block
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          # Name (description)
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u thelastchance -pMYSQL_PASS world < ./world-db/world.sql
      # Run the test
      - run:
          name: Run Unti Tests
          no_output_timeout: 30m
          command: |
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      # Store test results in xml file
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          npm test --forceExit
     
# Workflows
workflows:
  build_test:
    jobs:
      - run_tests

